#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# glb_to_three.py -- a .glb, packed into a .js file the browser can load
# without a server.
#
#   python3 tools/glb_to_three.py ../glb/dragon.glb boss-dragon
#   python3 tools/glb_to_three.py ../glb/dragon.glb boss-dragon --out assets/gltf
#
# WHY THIS EXISTS, AND WHY IT IS NOT tools/glb_to_model.py.
#
# `glb_to_model.py` BAKES a .glb: it reads the mesh, throws the textures and
# the materials away, quantises every surface down to a flat palette colour and
# writes plain number arrays into js/gl/models/*.js. That is exactly right for
# the nineteen regular enemies -- flat-shaded low-poly is the art style, the
# output is tiny, and nothing has to be loaded at runtime.
#
# It is exactly wrong for a hero unit. `glb/dragon.glb` carries a base-colour
# map, a metal/roughness map and a normal map, and the baked import of that
# same file (js/gl/models/enemy-dinomech.js) is EIGHT FLAT COLOURS. Everything
# the texture was for is gone before the browser ever sees it.
#
# So the hero units go through Three.js and GLTFLoader instead, which want the
# .glb ITSELF -- bytes, unmodified, textures and materials and armature intact.
#
# AND THAT IS THE WHOLE PROBLEM THIS FILE SOLVES. Getting bytes off disk into a
# browser normally means `fetch` or `XMLHttpRequest`, and AGENTS.md forbids both
# for a reason that is not stylistic: the game is opened by DOUBLE-CLICKING
# index.html, and over `file://` a browser blocks both outright. There is no
# server to fix it with, and adding one would change how the owner launches the
# game -- which is a hard constraint, not a preference.
#
# A <script> tag is not blocked. It is how all two hundred of the game's other
# files load. So the bytes are base64'd into a string literal inside a .js file,
# a <script> element pulls it in at runtime, and GLTFLoader.parse() -- which
# takes an ArrayBuffer rather than a URL -- reads it straight out of memory.
# No fetch, no XHR, no server, no CORS, and the load is still asynchronous
# because the tag is injected after the page is up rather than sitting in it.
#
# THE COST, STATED PLAINLY: base64 is 4/3 the size of the binary, and the file
# has to be REGENERATED whenever the art changes. That is the same standing
# obligation glb_to_model.py already carries, and it is the price of the
# double-click.
#
# The output declares itself generated and names its source, exactly as the
# generated model files do, so nobody edits one by hand.
# ---------------------------------------------------------------------------

import base64
import os
import struct
import sys


def read_glb_header(raw):
    """Sanity-check the container and report what is in it.

    A truncated or mislabelled file base64s just as happily as a good one and
    fails later, inside the loader, in the browser, as a stack trace nobody
    can connect back to this script. Cheaper to refuse it here.
    """
    if len(raw) < 12 or raw[:4] != b"glTF":
        raise SystemExit("not a binary glTF (.glb): missing the glTF magic")
    version, total = struct.unpack_from("<II", raw, 4)
    if version != 2:
        raise SystemExit("glTF version %d; this pipeline expects 2" % version)
    if total != len(raw):
        raise SystemExit(
            "header says %d bytes, file is %d -- truncated or padded"
            % (total, len(raw)))
    return version


def main(argv):
    if len(argv) < 3:
        raise SystemExit(
            "usage: glb_to_three.py <source.glb> <name> [--out DIR]")

    source = argv[1]
    name = argv[2]
    out_dir = "assets/gltf"
    if "--out" in argv:
        out_dir = argv[argv.index("--out") + 1]

    with open(source, "rb") as handle:
        raw = handle.read()
    read_glb_header(raw)

    payload = base64.b64encode(raw).decode("ascii")

    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    basename = os.path.basename(source)
    target = os.path.join(out_dir, basename + ".js")

    # ONE LONG LINE, DELIBERATELY. Splitting the literal across lines would
    # need either concatenation (which builds the whole string a second time in
    # the parser) or an array join, and neither buys anything: nobody reads
    # this file, and every editor that would struggle with the long line
    # struggles equally with the 5 MB.
    with open(target, "w") as handle:
        handle.write(
            "// GENERATED by tools/glb_to_three.py -- do not edit.\n"
            "// Source of truth is %s; re-run the packer.\n"
            "//\n"
            "// %d bytes of binary glTF, base64. Loaded by a <script> element\n"
            "// that js/gl/three-loader.js injects at runtime and handed to\n"
            "// GLTFLoader.parse() as bytes -- so nothing is ever fetched and\n"
            "// the game still opens by double-clicking index.html.\n"
            "window.TDGltfPayload = { name: \"%s\", bytes: %d, b64: \"%s\" };\n"
            % (basename, len(raw), name, len(raw), payload))

    print("%s -> %s" % (source, target))
    print("  %d bytes binary, %d bytes base64 (%.2fx)"
          % (len(raw), len(payload), len(payload) / float(len(raw))))
    print("  registers as \"%s\"" % name)


if __name__ == "__main__":
    main(sys.argv)
